import "@/styles/globals.css";
import Navbar from "@/components/Navigation/NavBar";
import Footer from "@/components/Navigation/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
